### ISSUE TITLE
google less secure is no more there !!!

### ISSUE THREAD

**Issue by coderatul** [coderatul/emailbomber#2]
sending gmails won't be a thing , as google considers smtplib mails as third party 
earlier i used less secure option but google has ended that feature 
now what to do ?

**Comment by cristiandiiorio** [comment]
I ran into the same problem but luckily now that less secure option has been ended you can access using an app password.   This tutorial explains how to generate and use app passwords. 
<href>https://support.google.com/accounts/answer/185833?hl=en</href>

**Comment by coderatul** [comment]
> I ran into the same problem but luckily now that less secure option has been ended you can access using an app password.   This tutorial explains how to generate and use app passwords. 
> <href>https://support.google.com/accounts/answer/185833?hl=en</href>
> 

Thanks for the help Buddy i really appreciate it ❤️
