### ISSUE TITLE
Count datatype exception handling

### ISSUE THREAD

**Issue by realhunter7869** [coderatul/emailbomber#3]
If there is some issue in count datatype... The user should be notified for the same rather then the program getting hard stopped... Will suggest implementing a try catch there... Would be happy to integrate...

**Comment by coderatul** [comment]
ok make a pull request i would love to see repo being developed

**Comment by Blastguy** [comment]
I can take care of this, looks like the original author went mia

**Comment by Blastguy** [comment]
Published PR, please give it a review
